### PR TITLE
adds favicon and team thumbnail for project page

### PR DESCRIPTION
**Pull request by Jakersnorth**
The version we forked did not have the thumbnails yet but we added our thumbnail to our main folder.

### CODE REVIEW

**Comment by karkar** [comment]
@Jakersnorth There's a conflict in your pull request. See if you can fix it on your end.

**Comment by karkar** [comment]
@Jakersnorth Update the fork and then submit a pull request.

**Comment by karkar** [comment]
@Jakersnorth Now the pull request is updating a yaml file outside your project folder in addition to massive conflicts. I would recommend the deleting this pull, doing a fresh fetch/pull of the fork, and the updating the files and submitting a new pull request.

**Comment by Jakersnorth** [comment]
Yeah I'm working on it. I tried merging the new files into our repo and git is modifying everyone elses files without me doing anything. I've done a fresh fork and clone about 3 times now and just cloning the new version of the repo down already causes widespread changes to other files.

**Comment by karkar** [comment]
If it's a single file change, I would recommend directly uploading the file
on the github repo of the course and creating a pull request from there. I
think that might be a bit more straightforward.

Let me know if that doesn't work.

Ravi

**Comment by Jakersnorth** [comment]
Ok, I did a new fork and swapped the files out with a new pull request

**Pull request closed without merging**
